project:
  type: website
  output-dir: _site

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left   # moves TOC into a sidebar
    toc-depth: 4     # include H2–H4
    toc-expand: 2    # expand them so you actually see H2 initially
    # toc-title: "On this page" 
    df-print: kable
    number-sections: true 
    page-layout: full   
    smooth-scroll: true
    embed-resources: true 

website:
  title: "R Labs for AREC 513 - Econometric Applications" 
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Lab 1"
        file: labs/lab1.qmd
      - text: "Lab 2"
        file: labs/lab2.qmd
      - text: "Lab 3"
        file: labs/lab3.qmd
      - text: "Lab 4"
        file: labs/lab4.qmd
      - text: "Lab 5"
        file: labs/lab5.qmd
      - text: "Lab 6"
        file: labs/lab6.qmd
    right:
      - text: "Answer Key"
        file: labs/answerkey.qmd
  page-footer: 
    left:
      - text: "© 2025 Liyuan Xuan — Built with Quarto"
        href: https://quarto.org

execute:
  echo: true 
  warning: false
  message: false
  freeze: false